/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FtlHolster {
        /**
          * Your Figma Personal Access Token. Find it under account settings from the top-left menu inside Figma.
         */
        "accessToken": string;
        /**
          * Your Figma file ID. https://www.figma.com/file/MYFILEID/my-file
         */
        "fileId": string;
        /**
          * A unique name for your test to display in the UI.
         */
        "name"?: string;
        /**
          * The node ID of the component you want to preview.
         */
        "node": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLFtlHolsterElement extends Components.FtlHolster, HTMLStencilElement {
    }
    var HTMLFtlHolsterElement: {
        prototype: HTMLFtlHolsterElement;
        new (): HTMLFtlHolsterElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ftl-holster": HTMLFtlHolsterElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface FtlHolster {
        /**
          * Your Figma Personal Access Token. Find it under account settings from the top-left menu inside Figma.
         */
        "accessToken"?: string;
        /**
          * Your Figma file ID. https://www.figma.com/file/MYFILEID/my-file
         */
        "fileId"?: string;
        /**
          * A unique name for your test to display in the UI.
         */
        "name"?: string;
        /**
          * The node ID of the component you want to preview.
         */
        "node"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "ftl-holster": FtlHolster;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ftl-holster": LocalJSX.FtlHolster & JSXBase.HTMLAttributes<HTMLFtlHolsterElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
