/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { configSettings, viewOptions } from "./components/ftl-buckle/ftl-buckle";
import { viewOptions as viewOptions1 } from "./components/ftl-buckle/ftl-buckle";
export namespace Components {
    interface FtlBelt {
        /**
          * Your Figma Personal Access Token. Find it under account settings from the top-left menu inside Figma.
         */
        "accessToken": string;
        /**
          * Your Figma file ID. https://www.figma.com/file/MYFILEID/my-file
         */
        "fileId": string;
    }
    interface FtlBuckle {
        "activeToggle": string;
        "mode": string;
        "opacity": string;
        "showGrid": boolean;
        "view": viewOptions;
    }
    interface FtlHolster {
        /**
          * Your Figma Personal Access Token. Find it under account settings from the top-left menu inside Figma.
         */
        "accessToken": string;
        "activeToggle": string;
        /**
          * Your Figma file ID. https://www.figma.com/file/MYFILEID/my-file
         */
        "fileId": string;
        /**
          * A unique name for your test to display in the UI.
         */
        "name"?: string;
        /**
          * The node ID of the component you want to preview.
         */
        "node": string;
        "opacity": string;
        "showGrid": boolean;
        "view": viewOptions1;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface FtlBuckleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFtlBuckleElement;
}
declare global {
    interface HTMLFtlBeltElement extends Components.FtlBelt, HTMLStencilElement {
    }
    var HTMLFtlBeltElement: {
        prototype: HTMLFtlBeltElement;
        new (): HTMLFtlBeltElement;
    };
    interface HTMLFtlBuckleElement extends Components.FtlBuckle, HTMLStencilElement {
    }
    var HTMLFtlBuckleElement: {
        prototype: HTMLFtlBuckleElement;
        new (): HTMLFtlBuckleElement;
    };
    interface HTMLFtlHolsterElement extends Components.FtlHolster, HTMLStencilElement {
    }
    var HTMLFtlHolsterElement: {
        prototype: HTMLFtlHolsterElement;
        new (): HTMLFtlHolsterElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ftl-belt": HTMLFtlBeltElement;
        "ftl-buckle": HTMLFtlBuckleElement;
        "ftl-holster": HTMLFtlHolsterElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface FtlBelt {
        /**
          * Your Figma Personal Access Token. Find it under account settings from the top-left menu inside Figma.
         */
        "accessToken"?: string;
        /**
          * Your Figma file ID. https://www.figma.com/file/MYFILEID/my-file
         */
        "fileId"?: string;
    }
    interface FtlBuckle {
        "activeToggle"?: string;
        "mode"?: string;
        "onFtl-on-change"?: (event: FtlBuckleCustomEvent<configSettings>) => void;
        "opacity"?: string;
        "showGrid"?: boolean;
        "view"?: viewOptions;
    }
    interface FtlHolster {
        /**
          * Your Figma Personal Access Token. Find it under account settings from the top-left menu inside Figma.
         */
        "accessToken"?: string;
        "activeToggle"?: string;
        /**
          * Your Figma file ID. https://www.figma.com/file/MYFILEID/my-file
         */
        "fileId"?: string;
        /**
          * A unique name for your test to display in the UI.
         */
        "name"?: string;
        /**
          * The node ID of the component you want to preview.
         */
        "node"?: string;
        "opacity"?: string;
        "showGrid"?: boolean;
        "view"?: viewOptions1;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "ftl-belt": FtlBelt;
        "ftl-buckle": FtlBuckle;
        "ftl-holster": FtlHolster;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ftl-belt": LocalJSX.FtlBelt & JSXBase.HTMLAttributes<HTMLFtlBeltElement>;
            "ftl-buckle": LocalJSX.FtlBuckle & JSXBase.HTMLAttributes<HTMLFtlBuckleElement>;
            "ftl-holster": LocalJSX.FtlHolster & JSXBase.HTMLAttributes<HTMLFtlHolsterElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
